/**
 * Cursor legs as timeline data. A leg is [moment ref, data-probe key]; the
 * harness resolves the ref, renders that frame with the probe, and takes the
 * element's centre. "park" leaves the frame beside the previous target. A key
 * ending in "?" is a hover: the hand travels there and rests without a press
 * (a change of mind before the real click). The result is a generated TS
 * module per format that the film's cursor reads.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Cursor, CursorLeg, LoadedConfig } from "../config.ts";
import { compositionFor, type Compiled } from "../timeline/schema.ts";
import { resolve } from "../timeline/resolve.ts";
import type { Engine } from "../render/engine.ts";
import { ensureDir } from "../util.ts";

/** same shape the film's GlobalCursor reads: part frame, film px, press or not */
export type CursorTarget = { id: string; frame: number; x: number; y: number; click: boolean; dwell?: number };

export type PlannedLeg = { ref: string; key: string; part: string; partFrame: number; filmFrame: number; park: boolean; hover: boolean; dwell?: number };

/** resolve every leg against the timeline; a bad ref or an empty key is an error naming the leg */
export const planLegs = (c: Compiled, legs: CursorLeg[]): PlannedLeg[] =>
  legs.map((leg, i) => {
    if (!Array.isArray(leg) || leg.length < 2 || leg.length > 3 || typeof leg[0] !== "string" || typeof leg[1] !== "string" || !leg[1]) throw new Error(`cursor leg #${i} must be [ref, key] or [ref, key, { dwell }], got ${JSON.stringify(leg)}`);
    const [ref, rawKey, legOpts] = leg;
    if (legOpts !== undefined && (typeof legOpts !== "object" || legOpts === null || (legOpts.dwell !== undefined && !(Number.isInteger(legOpts.dwell) && legOpts.dwell >= 0)))) throw new Error(`cursor leg #${i} options must be { dwell: frames >= 0 }, got ${JSON.stringify(legOpts)}`);
    const dwell = legOpts?.dwell;
    const hover = rawKey.endsWith("?");
    const key = hover ? rawKey.slice(0, -1) : rawKey;
    if (!key) throw new Error(`cursor leg #${i} must name a data-probe key before "?", got ${JSON.stringify(leg)}`);
    let L;
    try {
      L = resolve(c, ref);
    } catch (e) {
      throw new Error(`cursor leg #${i} "${ref}": ${(e as Error).message}`);
    }
    return { ref, key, part: L.part, partFrame: L.partFrame, filmFrame: L.filmFrame, park: key === "park", hover, ...(dwell !== undefined ? { dwell } : {}) };
  });

export const parkX = (width: number, side: Cursor["park"] = "right") => (side === "left" ? -120 : width + 120);

/** the parking spot beside the previous target: off frame, 140 px above the last press */
export const parkTarget = (leg: PlannedLeg, prev: CursorTarget | undefined, x: number): CursorTarget => ({ id: `${leg.ref} park`, frame: leg.partFrame, x, y: prev ? prev.y - 140 : 400, click: false });

/** the generated module, same text shape as the film's hand-written cursor-targets.ts */
export const targetsModule = (targets: CursorTarget[]): string =>
  `/* GENERATED by mh cursor from the harness DOM probe. Do not edit by hand. */
export type CursorTarget = { id: string; frame: number; x: number; y: number; click: boolean; dwell?: number };
export const CURSOR_TARGETS: CursorTarget[] = ${JSON.stringify(targets, null, 2)};
`;

/** writes only when the text differs, so an unchanged layout does not touch the source hash (and re-bundle everything) */
export const writeTargets = (file: string, targets: CursorTarget[]): { file: string; changed: boolean } => {
  const src = targetsModule(targets);
  if (existsSync(file) && readFileSync(file, "utf8") === src) return { file, changed: false };
  ensureDir(join(file, ".."));
  writeFileSync(file, src);
  return { file, changed: true };
};

/** render every leg's frame once per composition (batched), take the element centres, fill in the parks in film order */
export const measureLegs = async (
  e: Engine,
  cfg: LoadedConfig,
  c: Compiled,
  format: string,
  width: number,
  cursor: Cursor,
  opts: { settleMs?: number; concurrency?: number; log?: (s: string) => void } = {},
): Promise<CursorTarget[]> => {
  const legs = planLegs(c, cursor.legs);
  const px = parkX(width, cursor.park);
  const dir = ensureDir(join(cfg.cachePath, "probe", "cursor", format));
  const centres = new Map<string, { x: number; y: number }>();
  const byComp = new Map<string, PlannedLeg[]>();
  for (const l of legs) {
    if (l.park) continue;
    const compId = compositionFor(c.parts.find((p) => p.id === l.part)!, format);
    byComp.set(compId, [...(byComp.get(compId) ?? []), l]);
  }
  for (const [compId, ls] of byComp) {
    const frames = [...new Set(ls.map((l) => l.partFrame))];
    opts.log?.(`${compId}: ${frames.length} frames for ${ls.length} legs`);
    const outs = await e.stills(compId, frames.map((frame) => ({ frame, file: join(dir, `${compId}-f${frame}.png`) })), { probe: "probe", settleMs: opts.settleMs ?? 150, concurrency: opts.concurrency ?? 4 });
    for (const o of outs) {
      const items = o.probe?.items ?? [];
      for (const l of ls.filter((x) => x.partFrame === o.frame)) {
        const it = items.find((i) => i.key === l.key);
        if (!it) throw new Error(`cursor leg "${l.ref}" -> "${l.key}": no such data-probe at ${l.part} f${l.partFrame} (${format}). Keys there: ${items.filter((i) => i.kind === "probe").map((i) => i.key).join(", ") || "none"}`);
        centres.set(`${l.ref}\u0000${l.key}`, { x: Math.round(it.x + it.w / 2), y: Math.round(it.y + it.h / 2) });
      }
    }
  }
  const out: CursorTarget[] = [];
  for (const l of legs) {
    if (l.park) out.push(parkTarget(l, out[out.length - 1], px));
    else out.push({ id: `${l.ref} -> ${l.key}${l.hover ? " (hover)" : ""}`, frame: l.partFrame, ...centres.get(`${l.ref}\u0000${l.key}`)!, click: !l.hover, ...(l.dwell !== undefined ? { dwell: l.dwell } : {}) });
  }
  return out;
};
