/* GENERATED by mh cursor from the harness DOM probe. Do not edit by hand. */
export type CursorTarget = { id: string; frame: number; x: number; y: number; click: boolean };
export const CURSOR_TARGETS: CursorTarget[] = [
  {
    "id": "card.hover -> option-1",
    "frame": 30,
    "x": 1078,
    "y": 440,
    "click": true
  },
  {
    "id": "card.click -> option-1",
    "frame": 44,
    "x": 1078,
    "y": 440,
    "click": true
  },
  {
    "id": "card.reveal -> check-button",
    "frame": 52,
    "x": 512,
    "y": 615,
    "click": true
  },
  {
    "id": "card.reveal+12 park",
    "frame": 64,
    "x": 2040,
    "y": 475,
    "click": false
  },
  {
    "id": "map.score -> row-1",
    "frame": 110,
    "x": 960,
    "y": 411,
    "click": true
  },
  {
    "id": "map.score+16 park",
    "frame": 126,
    "x": 2040,
    "y": 271,
    "click": false
  }
];
