/* GENERATED by mh cursor from the harness DOM probe. Do not edit by hand. */
export type CursorTarget = { id: string; frame: number; x: number; y: number; click: boolean };
export const CURSOR_TARGETS: CursorTarget[] = [
  {
    "id": "card.hover -> option-1",
    "frame": 30,
    "x": 241,
    "y": 844,
    "click": true
  },
  {
    "id": "card.click -> option-1",
    "frame": 44,
    "x": 241,
    "y": 844,
    "click": true
  },
  {
    "id": "card.reveal -> check-button",
    "frame": 52,
    "x": 192,
    "y": 1103,
    "click": true
  },
  {
    "id": "card.reveal+12 park",
    "frame": 64,
    "x": 1200,
    "y": 963,
    "click": false
  },
  {
    "id": "map.score -> row-1",
    "frame": 110,
    "x": 540,
    "y": 731,
    "click": true
  },
  {
    "id": "map.score+16 park",
    "frame": 126,
    "x": 1200,
    "y": 591,
    "click": false
  }
];
