/**
 * Bundle the project once through a generated wrapper entry that mounts the
 * project's Root plus the harness probe. The wrapper lives inside the project
 * (cacheDir/entry) so `remotion` and `react` resolve to the project's copies.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { bundle } from "@remotion/bundler";
import type { LoadedConfig } from "../config.ts";
import { ensureDir, hashDir, hashString, ms } from "../util.ts";
import { PROBE_SOURCE } from "../probe/inject.ts";

const wrapperSource = (cfg: LoadedConfig, entryDir: string) => {
  let rootImport = relative(entryDir, cfg.rootPath).replace(/\\/g, "/").replace(/\.tsx?$/, "");
  if (!rootImport.startsWith(".")) rootImport = "./" + rootImport;
  const exportName = cfg.rootExport ?? "Root";
  return `/* generated by motion-harness, do not edit */
import React from "react";
import { registerRoot } from "remotion";
import { ${exportName} as ProjectRoot } from "${rootImport}";
${PROBE_SOURCE}
const HarnessRoot: React.FC = () => React.createElement(React.Fragment, null, React.createElement(ProjectRoot, null), React.createElement(HarnessProbe, null));
registerRoot(HarnessRoot);
`;
};

export type Bundled = { serveUrl: string; hash: string; fresh: boolean };

/** one bundle per source hash within a process: check, cursor and frames share it */
const memo = new Map<string, Bundled>();

export const bundleProject = async (cfg: LoadedConfig, opts: { force?: boolean; log?: (s: string) => void } = {}): Promise<Bundled> => {
  const log = opts.log ?? (() => {});
  const entryDir = ensureDir(join(cfg.cachePath, "entry"));
  const entry = join(entryDir, "index.tsx");
  const src = wrapperSource(cfg, entryDir);
  if (!existsSync(entry) || readFileSync(entry, "utf8") !== src) writeFileSync(entry, src);

  const outDir = join(cfg.cachePath, "bundle");
  const hashFile = join(cfg.cachePath, "bundle.hash");
  const hash = hashDir(cfg.projectDir, { ignore: ["public", "harness.config.ts"] }) + ":" + hashString(src) + ":" + (cfg.webpackOverride ? "wo" : "plain");
  const had = memo.get(outDir);
  if (had && had.hash === hash && !opts.force) return { ...had, fresh: false };
  if (!opts.force && existsSync(hashFile) && readFileSync(hashFile, "utf8") === hash && existsSync(join(outDir, "index.html"))) {
    log(`bundle up to date (${hash.slice(0, 12)})`);
    memo.set(outDir, { serveUrl: outDir, hash, fresh: false });
    return { serveUrl: outDir, hash, fresh: false };
  }
  const t0 = performance.now();
  const serveUrl = await bundle({
    entryPoint: entry,
    outDir,
    rootDir: cfg.projectDir,
    publicDir: cfg.publicPath,
    enableCaching: true,
    ignoreRegisterRootWarning: true,
    webpackOverride: (cfg.webpackOverride as any) ?? ((c: unknown) => c),
    onProgress: (p) => {
      if (p % 25 === 0) log(`bundling ${p}%`);
    },
  });
  writeFileSync(hashFile, hash);
  log(`bundled in ${ms(t0)} -> ${serveUrl}`);
  memo.set(outDir, { serveUrl, hash, fresh: true });
  return { serveUrl, hash, fresh: true };
};
