/**
 * Bundle the project once through a generated wrapper entry that mounts the
 * project's Root plus the harness probe. The wrapper lives inside the project
 * (cacheDir/entry) so `remotion` and `react` resolve to the project's copies.
 */
import { existsSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { bundle } from "@remotion/bundler";
import type { LoadedConfig } from "../config.ts";
import { ensureDir, hashDir, hashString, ms, newestMtime, readJson, writeJson } from "../util.ts";
import { PROBE_SOURCE } from "../probe/inject.ts";

export type BundleInfo = { hash: string; builtAt: string };
const infoPath = (cfg: LoadedConfig) => join(cfg.cachePath, "bundle.json");
export const bundleInfo = (cfg: LoadedConfig): BundleInfo | null => (existsSync(infoPath(cfg)) ? readJson<BundleInfo>(infoPath(cfg)) : null);

/** the project's source dir: `src/` next to the config when it exists, else the Root's dir */
export const projectSrcDir = (cfg: LoadedConfig) => (existsSync(join(cfg.projectDir, "src")) ? join(cfg.projectDir, "src") : dirname(cfg.rootPath));

/** files changed on disk after the current bundle was built: the config (never part of the bundle hash) and the compositions */
export const staleBundleWarnings = (cfg: LoadedConfig): string[] => {
  const info = bundleInfo(cfg);
  if (!info) return [];
  const built = Date.parse(info.builtAt);
  const out: string[] = [];
  const cfgM = statSync(cfg.configPath).mtimeMs;
  if (cfgM > built) out.push(`warning: ${cfg.configPath} changed after the bundle was built (${info.builtAt})`);
  const src = newestMtime(projectSrcDir(cfg));
  if (src && src.mtimeMs > built) out.push(`warning: ${src.file} changed after the bundle was built (${info.builtAt}); the next render or frames call rebundles`);
  return out;
};

const wrapperSource = (cfg: LoadedConfig, entryDir: string) => {
  let rootImport = relative(entryDir, cfg.rootPath).replace(/\\/g, "/").replace(/\.tsx?$/, "");
  if (!rootImport.startsWith(".")) rootImport = "./" + rootImport;
  const exportName = cfg.rootExport ?? "Root";
  return `/* generated by motion-harness, do not edit */
import React from "react";
import { registerRoot } from "remotion";
import { ${exportName} as ProjectRoot } from "${rootImport}";
${PROBE_SOURCE}
const HarnessRoot: React.FC = () => React.createElement(React.Fragment, null, React.createElement(ProjectRoot, null), React.createElement(HarnessProbe, null));
registerRoot(HarnessRoot);
`;
};

export type Bundled = { serveUrl: string; hash: string; fresh: boolean };

/** the hash the next bundle would get from the sources as they are now, no bundling: what "stale" is measured against */
export const currentBundleHash = (cfg: LoadedConfig): string => {
  const entryDir = join(cfg.cachePath, "entry");
  return hashDir(cfg.projectDir, { ignore: ["public", "harness.config.ts"] }) + ":" + hashString(wrapperSource(cfg, entryDir)) + ":" + (cfg.webpackOverride ? "wo" : "plain");
};

/** true when a run was rendered from other sources than the ones on disk now */
export const isStale = (runHash: string | undefined, nowHash: string) => !!runHash && runHash !== nowHash;

/** one bundle per source hash within a process: check, cursor and frames share it */
const memo = new Map<string, Bundled>();

export const bundleProject = async (cfg: LoadedConfig, opts: { force?: boolean; log?: (s: string) => void } = {}): Promise<Bundled> => {
  const log = opts.log ?? (() => {});
  const entryDir = ensureDir(join(cfg.cachePath, "entry"));
  const entry = join(entryDir, "index.tsx");
  const src = wrapperSource(cfg, entryDir);
  if (!existsSync(entry) || readFileSync(entry, "utf8") !== src) writeFileSync(entry, src);

  const outDir = join(cfg.cachePath, "bundle");
  const hashFile = join(cfg.cachePath, "bundle.hash");
  const hash = currentBundleHash(cfg);
  const had = memo.get(outDir);
  if (had && had.hash === hash && !opts.force) return { ...had, fresh: false };
  if (!opts.force && existsSync(hashFile) && readFileSync(hashFile, "utf8") === hash && existsSync(join(outDir, "index.html"))) {
    log(`bundle up to date (${hash.slice(0, 12)})`);
    memo.set(outDir, { serveUrl: outDir, hash, fresh: false });
    return { serveUrl: outDir, hash, fresh: false };
  }
  const t0 = performance.now();
  const serveUrl = await bundle({
    entryPoint: entry,
    outDir,
    rootDir: cfg.projectDir,
    publicDir: cfg.publicPath,
    enableCaching: true,
    ignoreRegisterRootWarning: true,
    webpackOverride: (cfg.webpackOverride as any) ?? ((c: unknown) => c),
    onProgress: (p) => {
      if (p % 25 === 0) log(`bundling ${p}%`);
    },
  });
  writeFileSync(hashFile, hash);
  writeJson(infoPath(cfg), { hash, builtAt: new Date().toISOString() } satisfies BundleInfo);
  log(`bundled in ${ms(t0)} -> ${serveUrl}`);
  memo.set(outDir, { serveUrl, hash, fresh: true });
  return { serveUrl, hash, fresh: true };
};
