/**
 * A delivery folder: the films per format, the stills, the subtitles, a manifest
 * with sizes, durations, bitrates, hashes and the chapter list from the timeline,
 * and a .gitignore that keeps the mp4 files out of the repo. The four commands a
 * hand delivery takes, as one.
 */
import { copyFileSync, existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import type { Compiled } from "../timeline/schema.ts";
import { fmtTime } from "../timeline/schema.ts";
import { chapterLines, srtEntries, srtText } from "../srt/srt.ts";
import { burnCaptions, type CaptionStyle } from "../srt/burn.ts";
import { PLATFORM_TARGETS, normalizeLoudness, loudnessVerdict } from "../audio/loudness.ts";
import { ensureDir, mediaStats, mb, sha1File, type MediaStats } from "../util.ts";

export type DeliveredFile = { kind: "film" | "web" | "still" | "srt" | "platform" | "captions"; format?: string; platform?: string; file: string; bytes: number; sha1: string; seconds?: number; kbps?: number; width?: number; height?: number; url?: string; loudness?: { lufs: number; truePeak: number } };

export type Delivery = { dir: string; film: string; files: DeliveredFile[]; manifest: string; gitignore: string };

export type DeliverInput = {
  film: string;
  c: Compiled;
  /** rendered masters per format (missing ones are skipped and reported) */
  films: { format: string; master: string; web?: string; size: { width: number; height: number } }[];
  /** rendered stills (png or jpg) */
  stills?: { id: string; file: string; width: number; height: number }[];
  lang?: string;
  /** per platform: a copy of each film normalised to that platform's loudness target */
  platforms?: string[];
  /** a copy of each film with the subtitles burned in; `bottom` per format */
  captions?: Omit<CaptionStyle, "bottom"> & { bottom?: Record<string, number> };
  /** upload every delivered file here and record the public urls */
  upload?: UploadTarget;
};

export type UploadTarget = { endpoint: string; bucket: string; prefix: string; accessKeyId: string; secretAccessKey: string; publicUrl?: string; region?: string };

/** S3-compatible target from the environment: MH_S3_* first, then the Cloudflare R2 names a project may already carry */
export const uploadTargetFromEnv = (prefix: string): UploadTarget => {
  const env = process.env;
  const endpoint = env.MH_S3_ENDPOINT ?? (env.CLOUDFLARE_ACCOUNT_ID ? `https://${env.CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com` : undefined);
  const bucket = env.MH_S3_BUCKET ?? env.CLOUDFLARE_BUCKET_NAME;
  const accessKeyId = env.MH_S3_KEY ?? env.CLOUDFLARE_ACCESS_KEY_ID ?? env.AWS_ACCESS_KEY_ID;
  const secretAccessKey = env.MH_S3_SECRET ?? env.CLOUDFLARE_SECRET_ACCESS_KEY ?? env.AWS_SECRET_ACCESS_KEY;
  if (!endpoint || !bucket || !accessKeyId || !secretAccessKey) throw new Error("upload needs MH_S3_ENDPOINT, MH_S3_BUCKET, MH_S3_KEY, MH_S3_SECRET (or CLOUDFLARE_ACCOUNT_ID, CLOUDFLARE_BUCKET_NAME, CLOUDFLARE_ACCESS_KEY_ID, CLOUDFLARE_SECRET_ACCESS_KEY) in the environment");
  return { endpoint, bucket, prefix: prefix.replace(/^\/+|\/+$/g, ""), accessKeyId, secretAccessKey, publicUrl: env.MH_S3_PUBLIC_URL, region: env.MH_S3_REGION ?? "auto" };
};

const contentType = (f: string) => (f.endsWith(".mp4") ? "video/mp4" : f.endsWith(".jpg") || f.endsWith(".jpeg") ? "image/jpeg" : f.endsWith(".png") ? "image/png" : f.endsWith(".srt") ? "text/plain; charset=utf-8" : f.endsWith(".md") ? "text/markdown; charset=utf-8" : "application/octet-stream");

/** put one file; returns the public url (publicUrl + key, else the S3 path) */
export const uploadFile = async (t: UploadTarget, file: string): Promise<string> => {
  const { S3Client, PutObjectCommand } = await import("@aws-sdk/client-s3");
  const s3 = new S3Client({ region: t.region ?? "auto", endpoint: t.endpoint, credentials: { accessKeyId: t.accessKeyId, secretAccessKey: t.secretAccessKey } });
  const key = `${t.prefix ? t.prefix + "/" : ""}${basename(file)}`;
  await s3.send(new PutObjectCommand({ Bucket: t.bucket, Key: key, Body: readFileSync(file), ContentType: contentType(file), CacheControl: "public, max-age=31536000, immutable" }));
  return t.publicUrl ? `${t.publicUrl.replace(/\/+$/, "")}/${key}` : `s3://${t.bucket}/${key}`;
};

const GITIGNORE = "# rendered films stay out of git; the CDN copies are the source of truth\n*.mp4\n*.mov\n";

export const manifestMarkdown = (inp: DeliverInput, files: DeliveredFile[], srtName: string | null, when: Date): string => {
  const { c } = inp;
  const lines: string[] = [];
  lines.push(`# ${inp.film} delivery (${when.toISOString().slice(0, 10)})`, "");
  lines.push(`Rendered from the timeline with motion-harness: ${c.scenes.length} scenes, ${c.dur} frames, ${c.seconds.toFixed(2)} s at ${c.fps} fps. Generated by \`mh deliver\`, regenerate instead of editing.`, "");
  const anyUrl = files.some((f) => f.url);
  lines.push("## Files", "", `| kind | format | file | size | length | bitrate | loudness | sha1 |${anyUrl ? " url |" : ""}`, `|---|---|---|---|---|---|---|---|${anyUrl ? "---|" : ""}`);
  for (const f of files) lines.push(`| ${f.kind}${f.platform ? ` ${f.platform}` : ""} | ${f.format ?? (f.width ? `${f.width}x${f.height}` : "")} | \`${basename(f.file)}\` | ${mb(f.bytes)} | ${f.seconds !== undefined ? `${f.seconds.toFixed(2)} s` : ""} | ${f.kbps !== undefined ? `${f.kbps} kbit/s` : ""} | ${f.loudness ? `${f.loudness.lufs.toFixed(1)} LUFS, ${f.loudness.truePeak.toFixed(1)} dBTP` : ""} | ${f.sha1} |${anyUrl ? ` ${f.url ?? ""} |` : ""}`);
  lines.push("");
  const entries = srtEntries(c, { lang: inp.lang && c.timeline.i18n?.[inp.lang] ? inp.lang : undefined });
  if (entries.length) {
    lines.push("## Chapters", "", "One line per subtitle entry, first pinned to 0:00 (YouTube wants the first chapter there). Paste into the description.", "");
    for (const l of chapterLines(entries)) lines.push(`- ${l}`);
    lines.push("");
  }
  lines.push("## Scenes", "", "| # | part | scene | film in | dur | text |", "|---|---|---|---|---|---|");
  for (const s of c.scenes) lines.push(`| ${s.index} | ${s.part} | ${s.id} | ${fmtTime(s.filmStart, c.fps)} | ${(s.dur / c.fps).toFixed(2)} s | ${(s.text?.join(" / ") ?? s.caption ?? "").replace(/\|/g, "\\|")} |`);
  lines.push("");
  if (c.timeline.audio?.length) {
    lines.push("## Audio", "");
    for (const a of c.timeline.audio) lines.push(`- ${a.id} (${a.kind}): \`${basename(a.file)}\` at ${String(a.at)}${a.gain !== undefined ? `, gain ${a.gain}` : ""}${a.trim ? `, trim ${a.trim[0]}-${a.trim[1]} s` : ""}${a.loop ? ", loop" : ""}`);
    lines.push("");
  }
  if (srtName) lines.push(`Subtitles: \`${srtName}\` (times from the timeline, same in every format).`, "");
  return lines.join("\n");
};

export const deliver = async (inp: DeliverInput, dir: string, opts: { log?: (s: string) => void; readmeName?: string } = {}): Promise<Delivery> => {
  const log = opts.log ?? (() => {});
  ensureDir(dir);
  const files: DeliveredFile[] = [];
  const add = async (kind: DeliveredFile["kind"], src: string, name: string, extra: Partial<DeliveredFile> = {}) => {
    const dst = join(dir, name);
    if (src !== dst) copyFileSync(src, dst);
    const st: MediaStats | null = kind === "film" || kind === "web" || kind === "platform" || kind === "captions" ? await mediaStats(dst) : null;
    const bytes = st?.bytes ?? readFileSync(dst).length;
    const entry: DeliveredFile = { kind, file: dst, bytes, sha1: sha1File(dst), ...(st ? { seconds: st.seconds, kbps: st.kbps } : {}), ...extra };
    files.push(entry);
    log(`  ${kind.padEnd(8)} ${name} (${mb(bytes)})`);
    return entry;
  };
  const langOk = inp.lang && inp.c.timeline.i18n?.[inp.lang] ? inp.lang : undefined;
  for (const f of inp.films) {
    if (!existsSync(f.master)) {
      log(`  film  ${f.format}: not rendered (${f.master}), skipped`);
      continue;
    }
    const aspect = `${f.size.width}x${f.size.height}`;
    const master = await add("film", f.master, `${inp.film}-${f.format}-${aspect}.mp4`, { format: f.format, width: f.size.width, height: f.size.height });
    // per platform: the same picture, sound normalised to what the platform measures
    for (const platform of inp.platforms ?? []) {
      const target = PLATFORM_TARGETS[platform];
      if (!target) throw new Error(`unknown platform "${platform}" (have: ${Object.keys(PLATFORM_TARGETS).join(", ")})`);
      const name = `${inp.film}-${f.format}-${aspect}-${platform}.mp4`;
      const { before, after } = await normalizeLoudness(master.file, join(dir, name), target);
      await add("platform", join(dir, name), name, { format: f.format, platform, width: f.size.width, height: f.size.height, loudness: { lufs: after.lufs, truePeak: after.truePeak } });
      log(`           ${platform}: ${before.lufs.toFixed(1)} -> ${after.lufs.toFixed(1)} LUFS (${loudnessVerdict(after, target)})`);
    }
    if (inp.captions) {
      const entries = srtEntries(inp.c, { lang: langOk });
      if (entries.length) {
        const name = `${inp.film}-${f.format}-${aspect}-captions${langOk ? `-${langOk}` : ""}.mp4`;
        const { bottom, ...style } = inp.captions;
        await burnCaptions(master.file, entries, f.size, { ...style, bottom: bottom?.[f.format] }, join(dir, name), join(dir, ".captions"));
        await add("captions", join(dir, name), name, { format: f.format, width: f.size.width, height: f.size.height });
      }
    }
    if (f.web && existsSync(f.web)) {
      // a web copy left over from an earlier render is not this film: skip it, say so
      if (statSync(f.web).mtimeMs < statSync(f.master).mtimeMs - 1000) log(`  web   ${f.format}: ${basename(f.web)} is older than the master (mh render --web makes a fresh one), skipped`);
      else await add("web", f.web, `${inp.film}-${f.format}-${aspect}-web.mp4`, { format: f.format, width: f.size.width, height: f.size.height });
    }
  }
  for (const s of inp.stills ?? []) {
    if (!existsSync(s.file)) continue;
    await add("still", s.file, `${s.id}${s.file.endsWith(".jpg") ? ".jpg" : ".png"}`, { width: s.width, height: s.height });
  }
  const entries = srtEntries(inp.c, { lang: langOk });
  let srtName: string | null = null;
  if (entries.length) {
    srtName = `${inp.film}-${inp.lang ?? "en"}.srt`;
    writeFileSync(join(dir, srtName), srtText(entries));
    await add("srt", join(dir, srtName), srtName);
  }
  if (inp.upload) {
    for (const f of files) {
      f.url = await uploadFile(inp.upload, f.file);
      log(`  up       ${basename(f.file)} -> ${f.url}`);
    }
  }
  const gitignore = join(dir, ".gitignore");
  if (!existsSync(gitignore)) writeFileSync(gitignore, GITIGNORE);
  // a hand-written README in the folder is never overwritten: the generated one goes next to it
  const readme = join(dir, opts.readmeName ?? "README.md");
  const manifest = existsSync(readme) && !readFileSync(readme, "utf8").includes("Generated by `mh deliver`") ? join(dir, "MANIFEST.md") : readme;
  writeFileSync(manifest, manifestMarkdown(inp, files, srtName, new Date()));
  return { dir, film: inp.film, files, manifest, gitignore };
};
