/**
 * A delivery folder: the films per format, the stills, the subtitles, a manifest
 * with sizes, durations, bitrates, hashes and the chapter list from the timeline,
 * and a .gitignore that keeps the mp4 files out of the repo. The four commands a
 * hand delivery takes, as one.
 */
import { copyFileSync, existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import type { Compiled } from "../timeline/schema.ts";
import { fmtTime } from "../timeline/schema.ts";
import { chapterLines, srtEntries, srtText } from "../srt/srt.ts";
import { ensureDir, mediaStats, mb, sha1File, type MediaStats } from "../util.ts";

export type DeliveredFile = { kind: "film" | "web" | "still" | "srt"; format?: string; file: string; bytes: number; sha1: string; seconds?: number; kbps?: number; width?: number; height?: number };

export type Delivery = { dir: string; film: string; files: DeliveredFile[]; manifest: string; gitignore: string };

export type DeliverInput = {
  film: string;
  c: Compiled;
  /** rendered masters per format (missing ones are skipped and reported) */
  films: { format: string; master: string; web?: string; size: { width: number; height: number } }[];
  /** rendered stills (png or jpg) */
  stills?: { id: string; file: string; width: number; height: number }[];
  lang?: string;
};

const GITIGNORE = "# rendered films stay out of git; the CDN copies are the source of truth\n*.mp4\n*.mov\n";

export const manifestMarkdown = (inp: DeliverInput, files: DeliveredFile[], srtName: string | null, when: Date): string => {
  const { c } = inp;
  const lines: string[] = [];
  lines.push(`# ${inp.film} delivery (${when.toISOString().slice(0, 10)})`, "");
  lines.push(`Rendered from the timeline with motion-harness: ${c.scenes.length} scenes, ${c.dur} frames, ${c.seconds.toFixed(2)} s at ${c.fps} fps. Generated by \`mh deliver\`, regenerate instead of editing.`, "");
  lines.push("## Files", "", "| kind | format | file | size | length | bitrate | sha1 |", "|---|---|---|---|---|---|---|");
  for (const f of files) lines.push(`| ${f.kind} | ${f.format ?? (f.width ? `${f.width}x${f.height}` : "")} | \`${basename(f.file)}\` | ${mb(f.bytes)} | ${f.seconds !== undefined ? `${f.seconds.toFixed(2)} s` : ""} | ${f.kbps !== undefined ? `${f.kbps} kbit/s` : ""} | ${f.sha1} |`);
  lines.push("");
  const entries = srtEntries(c);
  if (entries.length) {
    lines.push("## Chapters", "", "One line per subtitle entry, first pinned to 0:00 (YouTube wants the first chapter there). Paste into the description.", "");
    for (const l of chapterLines(entries)) lines.push(`- ${l}`);
    lines.push("");
  }
  lines.push("## Scenes", "", "| # | part | scene | film in | dur | text |", "|---|---|---|---|---|---|");
  for (const s of c.scenes) lines.push(`| ${s.index} | ${s.part} | ${s.id} | ${fmtTime(s.filmStart, c.fps)} | ${(s.dur / c.fps).toFixed(2)} s | ${(s.text?.join(" / ") ?? s.caption ?? "").replace(/\|/g, "\\|")} |`);
  lines.push("");
  if (c.timeline.audio?.length) {
    lines.push("## Audio", "");
    for (const a of c.timeline.audio) lines.push(`- ${a.id} (${a.kind}): \`${basename(a.file)}\` at ${String(a.at)}${a.gain !== undefined ? `, gain ${a.gain}` : ""}${a.trim ? `, trim ${a.trim[0]}-${a.trim[1]} s` : ""}${a.loop ? ", loop" : ""}`);
    lines.push("");
  }
  if (srtName) lines.push(`Subtitles: \`${srtName}\` (times from the timeline, same in every format).`, "");
  return lines.join("\n");
};

export const deliver = async (inp: DeliverInput, dir: string, opts: { log?: (s: string) => void; readmeName?: string } = {}): Promise<Delivery> => {
  const log = opts.log ?? (() => {});
  ensureDir(dir);
  const files: DeliveredFile[] = [];
  const add = async (kind: DeliveredFile["kind"], src: string, name: string, extra: Partial<DeliveredFile> = {}) => {
    const dst = join(dir, name);
    if (src !== dst) copyFileSync(src, dst);
    const st: MediaStats | null = kind === "film" || kind === "web" ? await mediaStats(dst) : null;
    const bytes = st?.bytes ?? readFileSync(dst).length;
    files.push({ kind, file: dst, bytes, sha1: sha1File(dst), ...(st ? { seconds: st.seconds, kbps: st.kbps } : {}), ...extra });
    log(`  ${kind.padEnd(5)} ${name} (${mb(bytes)})`);
  };
  for (const f of inp.films) {
    if (!existsSync(f.master)) {
      log(`  film  ${f.format}: not rendered (${f.master}), skipped`);
      continue;
    }
    const aspect = `${f.size.width}x${f.size.height}`;
    await add("film", f.master, `${inp.film}-${f.format}-${aspect}.mp4`, { format: f.format, width: f.size.width, height: f.size.height });
    if (f.web && existsSync(f.web)) {
      // a web copy left over from an earlier render is not this film: skip it, say so
      if (statSync(f.web).mtimeMs < statSync(f.master).mtimeMs - 1000) log(`  web   ${f.format}: ${basename(f.web)} is older than the master (mh render --web makes a fresh one), skipped`);
      else await add("web", f.web, `${inp.film}-${f.format}-${aspect}-web.mp4`, { format: f.format, width: f.size.width, height: f.size.height });
    }
  }
  for (const s of inp.stills ?? []) {
    if (!existsSync(s.file)) continue;
    await add("still", s.file, `${s.id}${s.file.endsWith(".jpg") ? ".jpg" : ".png"}`, { width: s.width, height: s.height });
  }
  const entries = srtEntries(inp.c);
  let srtName: string | null = null;
  if (entries.length) {
    srtName = `${inp.film}-${inp.lang ?? "en"}.srt`;
    writeFileSync(join(dir, srtName), srtText(entries));
    await add("srt", join(dir, srtName), srtName);
  }
  const gitignore = join(dir, ".gitignore");
  if (!existsSync(gitignore)) writeFileSync(gitignore, GITIGNORE);
  // a hand-written README in the folder is never overwritten: the generated one goes next to it
  const readme = join(dir, opts.readmeName ?? "README.md");
  const manifest = existsSync(readme) && !readFileSync(readme, "utf8").includes("Generated by `mh deliver`") ? join(dir, "MANIFEST.md") : readme;
  writeFileSync(manifest, manifestMarkdown(inp, files, srtName, new Date()));
  return { dir, film: inp.film, files, manifest, gitignore };
};
